version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-native-maps
    versions:
    - 0.15.2
    - 0.27.1
  - dependency-name: react-native-vector-icons
    versions:
    - 8.0.0
  - dependency-name: react-native
    versions:
    - 0.63.4
